### ISSUE TITLE
Presentation Ideas

### ISSUE THREAD

**Issue by lukestringer90** [SheffieldSwift/Operations#1]
Some of my thoughts on what would be applicable talking points for the first meetup.
- General "welcome to Sheffield Swift" house keeping stuff.
  - When every month
  - Where
  - Format - presentation, Q&A/discussion, pub?
  - Who we are
  - How to contact us
  - Where to find presentation content and resources - our GitHub repo
- Ask the attendees what their backgrounds are. Maybe a show of hands for Swift devs, Objective-C devs, Ruby devs, Python devs, etc
- A discussion of Swift's origins - it's relationship to Objective-C.
- A discussion of language fundamentals - staticly typed, OOP and functional etc
- A discussion of language features - focus on _unique_ features in Swift as talking about features other languages have (generics for example) will likely be less interesting.
  - Optionals (ktam 19 May)
  - Associative enum values and pattern matching. (ktam 19 May)
  - `var` and `let` - Swift's emphasis on immutability. (ktam 19 May)
  - Function syntax with named variables.
  - Functions as first order objects.
  - Memory management with ARC. (Not sure about this one).
- Where to find more information on Swift; recommended books and resource for learning Swift.
  - The official Swift Programming Language iBook
  - [Stanford course](http://web.stanford.edu/class/cs193p/cgi-bin/drupal/) teaching iOS dev with Swift. (I found this useful)
  - [Functional Swift book](http://www.objc.io/books/)
  - [Functional Swift snippets](http://www.objc.io/snippets/)
  - [The Week In Swift](https://swiftnews.curated.co)
  - [iOS Dev Weekly](https://iosdevweekly.com)
  - [NSHispter](http://nshipster.com) - all content now in Swift as well as Objective-C

**Comment by SheffieldKevin** [comment]
We can start from this. I think this covers quite a lot of material but the bits that should take appreciable time are the three discussion points on swift itself.

How do we break this up into who does what?

**Comment by lukestringer90** [comment]
@SheffieldKevin When we spoke you said you would be interested in doing an "Introduction To Swift" talk. Do you want to pick some of the more unique and interesting language feature and fundamentals and construct a talk around them?

I would be happy to do some sort of comparison with Objective-C as a follow up talk.

**Comment by SheffieldKevin** [comment]
I'm happy to do an introduction to Swift talk. I'm assuming the followup talk would be the following month? If that's your intention then I think that could work.

**Comment by lukestringer90** [comment]
Yes that would work for me. 

Do you want to detail some areas you want to cover on here and then we can start doing some "lite marketing" to get people interested?

**Comment by SheffieldKevin** [comment]
I'm thinking the following topics will be enough for the first meeting. If I have time to prepare beforehand to cover functions with named parameters and functions as first order objects I'll do so as well in case I breeze through Optionals, Associative Values, and var/let quickly.

Optionals (ktam 19 May)
Associative enum values and pattern matching. (ktam 19 May)
`var` and `let` - Swift's emphasis on immutability. (ktam 19 May)
Structs versus classes (highlighting differences between c primitive types, and ruby everything is an object)

**Comment by SheffieldKevin** [comment]
Also thinking this would be a nice video by @dimsumthinking https://www.youtube.com/watch?v=BVFtrrXhApw
