### ISSUE TITLE
August 18th Ideas

### ISSUE THREAD

**Issue by lukestringer90** [SheffieldSwift/Operations#2]
~~Preliminary idea: @domness (and possibly his co-developer) talk about what it's like to _actually_ build an app in Swift.~~

New idea: a **show and tell** meetup. Multiple speakers giving talks / demos of cool stuff they have done with Swift.
(Moved from previous [issue](https://github.com/SheffieldSwift/Materials/issues/1).)

**Comment by lukestringer90** [comment]
Ideas from @SheffieldKevin 

> Ask Glyn Williams to talk about converting objc to Swift.
> Do a push for a week to see if we can get an external speaker in.

**Comment by lukestringer90** [comment]
I've been playing around with the new Protocol features in Swift 2.0 (extensions, default implementations etc). I could give a short demo on this I think.

**Comment by SheffieldKevin** [comment]
> I've been playing around with the new Protocol features in Swift 2.0 (extensions, default implementations etc). I could give a short demo on this I think.

I'll be updating my playground Swift 2 on Tuesday and Wednesday for MobileNotts. I might possibly be able to do a short update for @SheffieldSwift on the 18th.

**Comment by lukestringer90** [comment]
Checking in to see who will be talking next week so we can get a bit of promo done:
- @lukestringer90 to talk about Swift 2.0 protocols.
- @SheffieldKevin to give an update on his Swift Intro playground.
- @steprescott to talk about porting Swift 2.0 code back to Obj-C.

@domness Is there anything you are able to prepare? Can you provide a synopsis?

**Comment by domness** [comment]
Oh, I thought it was a show and tell of what we had built, I was going to show two apps we worked on "Hello Sunday Morning" and "Graveyard Dash".

**Comment by lukestringer90** [comment]
@domness That would be great. I guess "Show and Tell and Miscellaneous" would be more accurate. So we have:
- @SheffieldKevin to talk about frameworks, linking, drawing and IBDesignable.
- @steprescott to talk about porting Swift 2.0 code back to Obj-C.
- @domness to show the "Hello Sunday Morning" and "Graveyard Dash" apps built in Swift.
- @matthew_spear to talk about what he learnt making his first app Countin'

I'll put some Tweets out tonight and an update on the Facebook event. @domness Are you the admin for the Eventbrite page? Can you update that also?

**Comment by domness** [comment]
Yeh, I can update the Eventbrite page :)

**Comment by SheffieldKevin** [comment]
The changes I made to the swift into playground were minimal. So I'm not sure that there will be value there.

**Comment by SheffieldKevin** [comment]
I was thinking as an alternative and this is a bit of a cheat, because the thing that is Swift about it is that the app in question is written in Swift.  

So my suggestion is showing how you get IBDesignable to work when the drawing code is within a framework in the Application bundle.

**Comment by lukestringer90** [comment]
@SheffieldKevin I think that is fine. 

As for my show and tell I think I'm going to have to pull out unfortunately. I'm not going to have time to put something together that will do justice to the new protocol features for Tuesday. Luckily we have a few more people now so we should be able to fill the time. 

I'm happy to do the introducing of speakers and what have you.
